services:
  mariadb:
    build:
      context: ./mysql
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/mariadb.conf.d:/etc/mysql/mariadb.conf.d
      - ./logs/mysql:/var/log/mysql

  php:
    build:
      context: ./php
    container_name: php
    restart: always
    depends_on:
      - mariadb
    env_file:
      - ./.env
    environment:
      APP_ENV_PATH: /var/www
    volumes:
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./php/conf.d:/usr/local/etc/php/conf.d
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./_src:/var/www/html
      - ./.env:/var/www/.env
      - ./logs/php:/var/log/php-fpm
      - ./logs/laravel:/var/www/html/storage/logs

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/scgi_params:/etc/nginx/scgi_params
      - ./_src:/var/www/html
      - ./logs/nginx:/var/log/nginx